services:
  app1: &app-config
    build: ..
    ports:
      - "8081:8080"
    environment:
      - PAYMENT_GATEWAY_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_GATEWAY_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "4.0"
#          memory: "4000MB"
    restart: unless-stopped
    depends_on:
      - redis

  app2:
    <<: *app-config
    ports:
      - "8082:8080"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly no
    networks:
      - backend
    deploy:
      resources:
        limits:
#          cpus: "2"
          memory: "15MB"
    restart: unless-stopped

  load-balancer:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    deploy:
      resources:
        limits:
#          cpus: "2"
          memory: "10MB"
    depends_on:
      - app1
      - app2

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true