spring:
  application:
    name: payment-processor-proxy

payment:
  gateway:
    url: ${PAYMENT_GATEWAY_DEFAULT:http://localhost:8001}
    fallback:
      url: ${PAYMENT_GATEWAY_FALLBACK:http://localhost:8002}

summary-service:
  url: ${SUMMARY_SERVICE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}