spring:
  application:
    name: payment-processor-proxy

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

payment:
  gateway:
    url: ${PAYMENT_GATEWAY_DEFAULT:http://localhost:8001}
    fallback:
      url: ${PAYMENT_GATEWAY_FALLBACK:http://localhost:8002}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}