spring:
  application:
    name: payment-processor-proxy
  jackson:
    serialization:
          write-dates-as-timestamps: false

payment:
  gateway:
    url: ${PAYMENT_GATEWAY_DEFAULT:http://localhost:8001}
    fallback:
      url: ${PAYMENT_GATEWAY_FALLBACK:http://localhost:8002}

summary-service:
  url: ${SUMMARY_SERVICE_URL:/tmp/spring-boot.sock}

unix:
  socket:
    path: ${SERVER_ADDRESS_URL:/tmp/spring-boot.sock}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}